'use client';

interface OptimizedImageProps {
  src: string;
  alt: string;
  width: number;
  height: number;
  sizes?: string;
  priority?: boolean;
  className?: string;
}

/**
 * Responsive image component with AVIF/WebP format negotiation and srcSet.
 * Uses <picture> element for progressive format fallback:
 *   AVIF (best compression) → WebP → original format
 *
 * Build-time variants are generated by scripts/optimize-images.mjs:
 *   -640w.avif, -1024w.avif, .avif
 *   -640w.webp, -1024w.webp, .webp
 *   -640w.{ext}, -1024w.{ext}, .{ext}
 */
export default function OptimizedImage({
  src,
  alt,
  width,
  height,
  sizes = '100vw',
  priority = false,
  className,
}: OptimizedImageProps) {
  const extMatch = src.match(/\.[^.]+$/);
  const ext = extMatch ? extMatch[0] : '.jpg';
  const basePath = src.replace(/\.[^.]+$/, '');

  return (
    <picture>
      {/* AVIF — best compression, checked first */}
      <source
        type="image/avif"
        srcSet={`${basePath}-640w.avif 640w, ${basePath}-1024w.avif 1024w, ${basePath}.avif ${width}w`}
        sizes={sizes}
      />
      {/* WebP — broad support fallback */}
      <source
        type="image/webp"
        srcSet={`${basePath}-640w.webp 640w, ${basePath}-1024w.webp 1024w, ${basePath}.webp ${width}w`}
        sizes={sizes}
      />
      {/* Original format — final fallback */}
      <img
        src={src}
        srcSet={`${basePath}-640w${ext} 640w, ${basePath}-1024w${ext} 1024w, ${src} ${width}w`}
        sizes={sizes}
        alt={alt}
        width={width}
        height={height}
        loading={priority ? 'eager' : 'lazy'}
        fetchPriority={priority ? 'high' : 'auto'}
        decoding={priority ? 'sync' : 'async'}
        className={className}
      />
    </picture>
  );
}
